#!/bin/bash

destFolder=$1
srcFolder=$2

currentPwd=${PWD}

mkdir -p "${destFolder}"

cd ../

echo "<!DOCTYPE HTML><html><head>" > "${destFolder}/index.html"
echo "<!-- generated by kheops builder -->" >> "${destFolder}/index.html"

# copy dependencies
cp -r "deps/earcut" "${destFolder}"
cp -r "deps/glMatrix" "${destFolder}"
cp -r "deps/urlParser" "${destFolder}"
cp "deps/webgl-utils.js" "${destFolder}"

echo "<!-- external libraries -->" >> "${destFolder}/index.html"
echo "<script type=\"text/javascript\" src=\"glMatrix/glMatrix-0.9.5.min.js\"></script>" >> "${destFolder}/index.html"
echo "<script type=\"text/javascript\" src=\"webgl-utils.js\"></script>" >> "${destFolder}/index.html"
echo "<script type=\"text/javascript\" src=\"urlParser/urlParser.js\"></script>" >> "${destFolder}/index.html"
echo "<script type=\"text/javascript\" src=\"earcut/earcut.js\"></script>" >> "${destFolder}/index.html"

# copy kheops library
kheopsFolder="${destFolder}/kheops"

mkdir -p "${kheopsFolder}"

cp "lib/kheops/core.js" "${kheopsFolder}"
cp "lib/kheops/vectors.js" "${kheopsFolder}"
cp "lib/kheops/primitive.js" "${kheopsFolder}"
cp "lib/kheops/planePrimitive.js" "${kheopsFolder}"
cp "lib/kheops/cubicPrimitive.js" "${kheopsFolder}"
cp "lib/kheops/cylindricPrimitive.js" "${kheopsFolder}"
cp "lib/kheops/object.js" "${kheopsFolder}"
cp "lib/kheops/sequencer.js" "${kheopsFolder}"
cp "lib/kheops/transform.js" "${kheopsFolder}"
cp "lib/kheops/light.js" "${kheopsFolder}"
cp "lib/kheops/drawingContext.js" "${kheopsFolder}"
cp "lib/kheops/scene.js" "${kheopsFolder}"
cp "lib/kheops/shaders.js" "${kheopsFolder}"
cp "lib/kheops/shadersDesc.js" "${kheopsFolder}"
cp "lib/kheops/textures.js" "${kheopsFolder}"
cp "lib/kheops/models.js" "${kheopsFolder}"
cp "lib/kheops/materials.js" "${kheopsFolder}"
cp "lib/kheops/materialsDesc.js" "${kheopsFolder}"
cp "lib/kheops/geometry.js" "${kheopsFolder}"
cp -r "lib/kheops/shaders" "${kheopsFolder}"

echo "<!-- kheops -->" >> "${destFolder}/index.html"
echo "<script type=\"text/javascript\" src=\"kheops/core.js\"></script>" >> "${destFolder}/index.html"
echo "<script type=\"text/javascript\" src=\"kheops/vectors.js\"></script>" >> "${destFolder}/index.html"
echo "<script type=\"text/javascript\" src=\"kheops/primitive.js\"></script>" >> "${destFolder}/index.html"
echo "<script type=\"text/javascript\" src=\"kheops/planePrimitive.js\"></script>" >> "${destFolder}/index.html"
echo "<script type=\"text/javascript\" src=\"kheops/cubicPrimitive.js\"></script>" >> "${destFolder}/index.html"
echo "<script type=\"text/javascript\" src=\"kheops/cylindricPrimitive.js\"></script>" >> "${destFolder}/index.html"
echo "<script type=\"text/javascript\" src=\"kheops/object.js\"></script>" >> "${destFolder}/index.html"
echo "<script type=\"text/javascript\" src=\"kheops/transform.js\"></script>" >> "${destFolder}/index.html"
echo "<script type=\"text/javascript\" src=\"kheops/sequencer.js\"></script>" >> "${destFolder}/index.html"
echo "<script type=\"text/javascript\" src=\"kheops/light.js\"></script>" >> "${destFolder}/index.html"
echo "<script type=\"text/javascript\" src=\"kheops/drawingContext.js\"></script>" >> "${destFolder}/index.html"
echo "<script type=\"text/javascript\" src=\"kheops/scene.js\"></script>" >> "${destFolder}/index.html"
echo "<script type=\"text/javascript\" src=\"kheops/shaders.js\"></script>" >> "${destFolder}/index.html"
echo "<script type=\"text/javascript\" src=\"kheops/shadersDesc.js\"></script>" >> "${destFolder}/index.html"
echo "<script type=\"text/javascript\" src=\"kheops/textures.js\"></script>" >> "${destFolder}/index.html"
echo "<script type=\"text/javascript\" src=\"kheops/models.js\"></script>" >> "${destFolder}/index.html"
echo "<script type=\"text/javascript\" src=\"kheops/materials.js\"></script>" >> "${destFolder}/index.html"
echo "<script type=\"text/javascript\" src=\"kheops/materialsDesc.js\"></script>" >> "${destFolder}/index.html"
echo "<script type=\"text/javascript\" src=\"kheops/geometry.js\"></script>" >> "${destFolder}/index.html"

# copy project components (index.js, textures files, models files)
if [ -d "${srcFolder}" ]; then

	echo "<!-- project -->" >> "${destFolder}/index.html"

	if [ -d "${srcFolder}/models" ]; then
		cp -r "${srcFolder}/models" "${destFolder}"
	fi

	if [ -d "${srcFolder}/model" ]; then
		cp -r "${srcFolder}/model" "${destFolder}"
	fi

	if [ -d "${srcFolder}/textures" ]; then
		cp -r "${srcFolder}/textures" "${destFolder}"
	fi

	if [ -f "${srcFolder}/resources.list" ]; then

		cp "${srcFolder}/resources.list" "${destFolder}"
		dos2unix "${destFolder}/resources.list" 2>&1
		while read _fileIter
		do
			if [ -d "${srcFolder}/${_fileIter}" ]; then
				echo "copying ${srcFolder}/${_fileIter} folder"
				cp -r "${srcFolder}/${_fileIter}" "${destFolder}"
			fi
			if [ -f "${srcFolder}/${_fileIter}" ]; then
				echo "copying ${srcFolder}/${_fileIter} file"
				cp "${srcFolder}/${_fileIter}" "${destFolder}"

				if [[ "${_fileIter}" =~ ^.*.js$ ]]; then
					echo "<script type=\"text/javascript\" src=\"${_fileIter}\"></script>" >> "${destFolder}/index.html"
				fi
			fi
		done < "${destFolder}/resources.list"
	fi

	if [ -f "${srcFolder}/index.js" ]; then
		cp "${srcFolder}/index.js" "${destFolder}"
		echo "<script type=\"text/javascript\" src=\"index.js\"></script>" >> "${destFolder}/index.html"
	fi	

    echo "<body><canvas id=\"webgl_canvas\" style=\"border:none\"></canvas></body></html>" >> "${destFolder}/index.html"

 	if [ -f "${srcFolder}/index.html" ]; then
		cp "${srcFolder}/index.html" "${destFolder}"
	fi
fi

